# .rubocop.yml
AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'db/queue_schema.rb'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'bin/bundle'
    - '.rubocop.yml'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'db/seeds.rb'
    - 'db/queue_schema.rb'
    - 'lib/tasks/**/*.rake'
    - 'lib/rails_admin/**/*'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'lib/tasks/**/*.rake'

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Exclude:
    - 'lib/tasks/**/*.rake'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/tasks/**/*.rake'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/tasks/**/*.rake'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true